---
title: " "
pagetitle: "Joanna Zyprych-Walczak"
---

<link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="academicicons/css/academicons.min.css"/>

## Invited

\item[19-11.2021] XXIX Międzynarodowy Kongres Medycyny Weterynaryjnej Małych Zwierząt PSLWMZ, Łódź;\\
 {\small Nowacka-Woszuk J., Szczerbal I., Stachowiak M., Szydłowski M., Szabelska-Beręsewicz A., Zyprych-Walczak J., Nowak T., Niżański W., Dzimira S., Łukomska A., Houszka M., Gogulski M., Stachecka J., Badura M., Świtoński M.\textsl{Zaburzenia rozwoju płci samic psa i kota - spojrzenie genetyka.}}
 
 \item[19-11.2021] XXIX Międzynarodowy Kongres Medycyny Weterynaryjnej Małych Zwierząt PSLWMZ, Łódź;\\
 {\small  Stachowiak M., Nowacka-Woszuk J., Krzemińska P., Szabelska-Beręsewicz A., Zyprych-Walczak J., Nowak T., Sosiński O., Woga W., Świtoński M. \textsl{Wnętrostwo psów - poszukiwanie predysponujących markerów genetycznych.}}

\item[02-04.09.2021] IX Zjazd Towarzystwa Biologii Rozrodu : Konferencja on-line, Poznań;\\ 
 {\small Nowacka-Woszuk J., Stachowiak M., Szczerbal I., Szydlowski M., Szabelska-Beręsewicz A., Zyprych-Walczak J., Nowak T., Krzeminska P., Świtonski M. \textsl{Whole genome sequencing in searching for genetic background of disorders of sex development in French Bulldog, American Stafford Terrier and Yorkshire Terriers dogs.}}
 
\item[02-04.09.2021] IX Zjazd Towarzystwa Biologii Rozrodu : Konferencja on-line, Poznań;\\
{\smal Stachowiak M., Szabelska-Beręsewicz A., Zyprych-Walczak J., Nowak T., Krzeminska P., Sosinski O., Nowacka-Woszuk J., Świtonski M. \textsl{Extensive differences of gene expression profiles between descended and undescended canine testes revealed by whole transcriptome sequencing (RNA-seq).}}


\item[14.11-15.11.2018]	ICCVS Fall Scientific Symposium 2018, Gdańsk;\\
{\small  Szabelska-Beręsewicz A., Zyprych-Walczak J.: \textsl{Statistical Analysis of RNA-seq Data - Bringing Results to Scientists.} - wygłoszenie zaproszonego referatu}

\item[20.08-24.08.2018]	The International Conference on Trends and Perspectives in Linear Statistical Inference - LinStat'2018, Będlewo k. Poznania;\\
{\small Szabelska-Beręsewicz A., Okoniewski M., Siatkowski I.: \textsl{Statistical methods for genes selection based on RNA-seq coverage profiles.} - współautor referatu}
{\small Zyprych-Walczak J., Szabelska-Beręsewicz A., Siatkowski I., Leśniewska A., Okoniewski M.: \textsl{Effect of gene-gene correlation in RNA-seq data analysis.} - poster}
\item[08.07-13.07.2018]	The 29th International Biometric Conference - IBC2018, Barcelona;\\
{\small Szabelska-Beręsewicz A., Zyprych-Walczak J., Siatkowski I., Okoniewski M.: \textsl{The difficult genes and their impact on RNA-seq data analysis.} - współautor referatu}

\item[17.09-20.09.2018] XV Overall Polish in vitro Culture and Plant Biotechnology Conference: Biotechnological utilization of in vitro culture variability, Rogów.\\
{\small Weigt D., Mikołajczyk S., Niemann J., Tomkowiak A., Kurasiak-Popowska D., Zyprych-Walczak J., Siatkowski I.: 
\textsl{The effect of zearalenone on the anther culture of wheat} - współautor referatu}}

\item[19.03-22.03.2018] XXVI Szkoła Zimowa Hodowców Bydła, Zakopane.\\
{\small Różańska-Zawieja J., Sobek Z., Winnicki S., Szabelska-Beręsewicz A., Siatkowski I.,  Zyprych-Walczak J.:
\textsl{Ocena wydajności stada na podstawie częściowych laktacji} - współautor referatu}

\item[10.09-14.09.2017]	The 47th International Biometrical Colloquium, Kiry k. Zakopanego;\\
{\small Szabelska-Beręsewicz A., Zyprych-Walczak J., Siatkowski I.: \textsl{Implementation of testing the parallelism for four-parameter logistic model in R.} - poster}

\item[22.07-23.07.2017]	16th International conference of Critical Assessment of Massive Data Analysis - CAMDA 2017, Praga;
{\small Leśniewska A., Szabelska-Beręsewicz A., Zyprych-Walczak J., Okoniewski M.: \textsl{Analysis of CAMDA RNA-seq data with the knowlegde of protein domains in genes.} - współautor referatu}
\item[24.11.2016]	RBioMeSs – R and Bioinformatics/Medical statistics, Warszawa
{\small Szabelska-Beręsewicz A. i Zyprych-Walczak J.: \textsl{Discussion of a biologist with a statistician working with R - how to find useful information in the vastness of biological data.} - wygłoszenie zaproszonego referatu}
\item[12.10-15.10.2016]	IV Kongres Onkologii Polskiej, Łódź;
{\small Szenajch J., Góralski M., Świercz A., Szabelska A., Zyprych-Walczak J., Synowiec A., Siatkowski I., Handschuh L.: \textsl{Zmiany w ekspresji szlaków sygnałowych uczestniczące w wykształcaniu nabytej w obecności erytropoetyny oporności na cisplatynę i paklitaksel w komórkach ludzkiego raka jajnika.} - współautor referatu}
\item[12.10-14.10.2016]	European R Users Meeting - eRum 2016, Poznań - organizator konferencji;
\item[21.09-23.09.2016]	LXXXI Zjazd Naukowy Polskiego Towarzystwa Zootechnicznego, Warszawa;
{\small Różalska-Zawieja J., Szabelska A., Nienartowicz-Zdrojewska A., Sobek Z., Siatkowski I., Zyprych-Walczak J.: \textsl{Accuracy of the selected linear models applied for estimation of the heritability coefficient in the dairy cattle population. - współautor referatu}}\\ 
{\small Różalska-Zawieja J., Szabelska A., Nienartowicz-Zdrojewska A., Sobek Z., Siatkowski I., Zyprych-Walczak J.: \textsl{ Herds influence of the heritability of pregnency length in the dairy cattle population. - współautor referatu}}\\
{\small Różalska-Zawieja J., Szabelska A., Nienartowicz-Zdrojewska A., Sobek Z., Siatkowski I., Zyprych-Walczak J.: \textsl{Influence of the paternity group size of the heritability of pregnancy length in dairy cattle population. - współautor referatu}}\\
\item[05.09-07.09.2016]	The 46th International Biometrical Colloquium, Lublin;
{\small Siatkowski I., Szabelska A., Zyprych-Walczak J.: \textsl{Statistical methods for survival data analysis. - poster}}


\item[16.06--18.06.2016] BioInformatics in Torun 2016 - BIT16, Toruń;\\
{\small Szabelska A., Zyprych-Walczak J., Siatkowski I., Okoniewski M.: \textsl{Influence of the primary analysis on discovering differentially expressed genes based on RNA-Seq data.} (poster)} 
\item[07.09--09.09.2015] The 45th International Biometrical Colloquium, Dymaczewo 2015;\\
{\small Zyprych-Walczak J., Szabelska A., Handschuh L., Górczak K., Klamecka K., Figlerowicz M. and Siatkowski I.: \textsl{The comparison of the normalization methods for RNA-Seq data analysis.} (współautor referatu)} 
\item[30.11--05.12.2014]	XL Konferencja Statystyka Matematyczna, Będlewo;\\
{\small Zyprych-Walczak J., Szabelska A., Siatkowski I.: \textsl{Przegląd problemów i metod związanych z analizą danych dotyczących ekspresji genów na podstawie eksperymentu głębokiego sekwencjonowania.} (wygłoszenie referatu)}
\item[15.10--17.10.2014]Polish Academic R Users Meeting - PAZUR 2014, Poznan;\\
{\small Szabelska A., Zyprych-Walczak J.: \textsl{Introduction to R} (prowadzenie warsztatów)}\\
{\small Szabelska A., Zyprych-Walczak J.: \textsl{Usage of R in the analysis of RNA-seq data} (współautor referatu)}\\
\item[30.06--4.07.2014]X Working Seminar on Statistical Methods in Variety Testing, Bedlewo;\\
{\small Gorczak K., Klamecka K., Szabelska A., Zyprych-Walczak J., Siatkowski I.: \textsl{RNA-Seq plant data analysis} (współautor referatu)}
\item[21.05.2014	] Open lectures in statistics, UAM Poznan;\\
{\small Zyprych-Walczak J., Szabelska A., Klamecka K., Gorczak K., Siatkowski I.: \textsl{Statistical analysis of data coming from microarray and next generation sequencing experiments} (wygłoszenie referatu)}
\item[26.11.2013] Seminar of the Bioinformatics Group, BOKU University, Vienna;\\
{\small Szabelska A., Zyprych-Walczak J., Siatkowski I.: \textsl{Microarrays vs RNA-seq - novel approaches for searching interesting genes} (wygłoszenie zaproszonego referatu)}
\item[18.04--20.04.2012] Congress of Polish Statistics, Poznan;\\
{\small Zyprych-Walczak J., Szabelska A., Siatkowski I.: \textsl{Metody selekcji genow uwzgledniajace korelacje pomiedzy genami} (wygłoszenie referatu)}
\item[8.12--9.12.2011] European Bioconductor Developers' Meeting 2011, Manchester;\\
{\small Okoniewski M. J., Lesniewska A., Szabelska A., Zyprych-Walczak J.: \textsl{Measures of dissimilarity of the coverage functions} (współautor referatu)} 
\item[5.09--08.09.2011] XLI International Biometricum Colloquium, Lublin;\\ 
{\small Szabelska A., Zyprych-Walczak J., Siatkowski I.: \textsl{Wykorzystanie liniowego modelu mieszanego w problemie selekcji genów} (współautor referatu)}


2021 International Conference on Statistics for Twenty-First Century, virtual: *Brief Introduction to Phase II Trials in Oncology*

2021 Joint Statistical Meetings, virtual: *Correlating Surrogate Endpoints with Overall Survival at the Individual Patient Level for Precision Oncology* ([slides](https://github.com/zabore/slidedecks/blob/master/Zabor-JSM2021.pdf))

2021 American Urological Association Methods in Clinical Urology Research (MCURe) Workshop, virtual: *Reporting Effect Size and Precision in Clinical Research*

2021 International Indian Statistical Association Conference, virtual: *Bayesian basket trial design with false discovery rate control* ([slides](https://github.com/zabore/slidedecks/blob/master/zabor_iisa2021.pdf))

2020 Greater Cleveland R Group, virtual: *Creating presentation-ready summary tables with {gtsummary}* ([slides](http://www.emilyzabor.com/cleveland-r-gtsummary/#1))

2020 Cleveland Clinic Florida Cancer Grand Rounds, Weston, FL: *Etiologic heterogeneity in cancer*

2018 Memorial Sloan Kettering Cancer Center Department of Epidemiology & Biostatistics, New York, NY: *Statistical methods for the study of etiologic heterogeneity*

2018 Cleveland Clinic Department of Quantitative Health Sciences, Cleveland, OH: *Statistical methods for the study of etiologic heterogeneity*

2018 NYU School of Medicine Department of Population Health, Division of Biostatistics, New York, NY: *Statistical methods for the study of etiologic heterogeneity*

2018 Mayo Clinic Department of Health Sciences Research, Rochester, MN: *Validity of a method for identifying etiologically heterogeneous disease subtypes*

2018 R/Medicine, New Haven, CT: *Teaching Survival Analysis to Clinical Collaborators*

2018 New York R Conference, New York, NY: *How Long Will I Live? The Statistics Behind Prognosis in Cancer Research*


## Contributed

2021 R/Medicine Conference, virtual: *Designing early phase clinical trials with {ppseq}* ([slides](http://www.emilyzabor.com/rmedicine2021))

2018 Joint Statistical Meetings, Vancouver, BC, Canada: *Validity of a method for identifying disease subtypes that are etiologically heterogeneous*

2018 Eastern North American Region of the International Biometric Society, Atlanta, GA: *Validity of a method for identifying disease subtypes that are etiologically heterogeneous*

2017 Joint Statistical Meetings, Baltimore, MD: *Dimension reduction in the study of etiologic heterogeneity*

2017 Society for Epidemiologic Research, Seattle, WA: *A comparison of statistical methods for the study of etiologic heterogeneity* (poster)

2017 Eastern North American Region of the International Biometric Society, Washington DC: *A comparison of statistical methods for the study of etiologic heterogeneity* (poster)

2016 Molecular Pathologic Epidemiology, Boston, MA: *A review of statisitcal methods for evaluating etiologic heterogeneity*

2011 Third North American American Congress of Epidemiology, Montreal, Canada: *Initial reactions to tobacco and risk of future regular tobacco use* (poster)

2010 American Association for Dental Research, Washington DC: *Association between periodontal disease, bacterial vaginosis, and sexual risk behaviours*



